version: '3.8'

services:
  gateway:
    container_name: notify-gateway
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 10000:10000
    networks:
      - micro-notify-network
  outbox:
    container_name: notify-gateway-outbox
    env_file:
      - .env
    build:
      dockerfile: outbox.Dockerfile
      context: ./
    networks:
      - micro-notify-network

networks:
  micro-notify-network:
    external: true
