version: '3.8'

services:
  gateway:
    container_name: notify-gateway
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    networks:
      - micro-network
  outbox:
    container_name: notify-gateway-outbox
    env_file:
      - .env
    build:
      dockerfile: outbox.Dockerfile
    networks:
      - micro-network
networks:
  micro-network:
    external: true