import os
from dotenv import load_dotenv

load_dotenv()

POSTGRES_USER=os.getenv("NOTIFICATION_POSTGRES_USER")
POSTGRES_PASSWORD=os.getenv("NOTIFICATION_POSTGRES_PASSWORD")
POSTGRES_HOST=os.getenv("NOTIFICATION_POSTGRES_HOST")
POSTGRES_PORT=os.getenv("NOTIFICATION_POSTGRES_PORT")
POSTGRES_DB=os.getenv("NOTIFICATION_POSTGRES_DB")
POSTGRES_URL=f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"


RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD=os.getenv("RABBITMQ_PASSWORD")
RABBITMQ_HOST=os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT=os.getenv("RABBITMQ_PORT")
RABBITMQ_URL=f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}/"

queues = {
    "email": os.getenv("EMAIL_QUEUE"),
}