email:
  queue:
    notify: notify-email
    events: email-events

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    detailed:
      format: "%(asctime)s %(name)s %(levelname)s [%(filename)s:%(lineno)d] - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout

    app_logs:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: detailed
      filename: "log/app.log"
      maxBytes: 104857600
      backupCount: 5

  loggers:
    root:
      handlers: []
      level: DEBUG

    app:
      handlers: [console, app_logs]
      level: DEBUG
      propagate: false
